version: '3.8'
services:
  pg_db:
    image: postgres:latest
    container_name: pg_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgres/data
  
  redis_db:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Porta padrão para conexões RabbitMQ
      - "15672:15672" # Porta para a interface de gerenciamento web
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  user-api:
    image: randandel/user-service:latest
    build:
     context: .
     dockerfile: services/user/User.API/dockerfile
    environment:
     - ASPNETCORE_ENVIRONEMT= Development
    depends_on:
     - pg_db
     - redis_db
     - rabbitmq

  
volumes:
 pg-data:
 redis-data:
 rabbitmq-data:   