version: '3.8'

services:
  pg_db:
    image: postgres:latest
    container_name: pg_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - dev

  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - "6379:6379" 
    volumes:
      - redis-data:/data
    networks:
      - dev

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - dev

  user-service:
    image: randandel/user-service:latest
    build:
      context: .
      dockerfile: services/user/User.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JwtSettings__Secret=CF6F07A3B43D4A6B5F9F5DE7687A392C6E71E2AABD7D2D83CFB0F58B6CE6C369
      - S3Image__Bucket=
      - S3Image__Key=
      - S3Image__Secret=
      - Redis__HostName=cache
      - Redis__Port=6379
      - Rabbitmq__HostName=rabbitmq 
      - Rabbitmq__UserName=user 
      - Rabbitmq__Password=password 
      - Rabbitmq__RetryCount=5 
    ports:
      - "8080:80" 
    networks:
      - dev
    depends_on:
      - pg_db
      - cache
      - rabbitmq

  vehicle-service:
    image: randandel/vehicle-service:latest
    build:
      context: .
      dockerfile: services/vehicle/Vehicle.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JwtSettings__Secret=CF6F07A3B43D4A6B5F9F5DE7687A392C6E71E2AABD7D2D83CFB0F58B6CE6C369
      - Postgres__ConnectionString=Host=pg_db;Username=postgres;Password=postgres;Database=catalog; PORT=5432
      - Rabbitmq__HostName=rabbitmq 
      - Rabbitmq__UserName=user 
      - Rabbitmq__Password=password 
      - Rabbitmq__RetryCount=5 
      - AwsNotify__accessKey=
      - AwsNotify__secretKey=
      - AwsNotify__region=sa-east-1
      - AwsNotify__urlQueue=https://sqs.sa-east-1.amazonaws.com/653328364873
    ports:
      - "8081:80" 
    networks:
      - dev
    depends_on:
      - pg_db
      - cache
      - rabbitmq

  order-service:
    image: randandel/order-service:latest
    build:
      context: .
      dockerfile: services/order/Order.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JwtSettings__Secret=CF6F07A3B43D4A6B5F9F5DE7687A392C6E71E2AABD7D2D83CFB0F58B6CE6C369
      - Postgres__ConnectionString=Host=pg_db;Username=postgres;Password=postgres;Database=catalog; PORT=5432
      - Rabbitmq__HostName=rabbitmq 
      - Rabbitmq__UserName=user 
      - Rabbitmq__Password=password 
      - Rabbitmq__RetryCount=5 
    ports:
      - "8082:80" 
    networks:
      - dev
    depends_on:
      - pg_db
      - cache
      - rabbitmq
   
  notify-service:
    image: randandel/notify-service:latest
    build:
      context: .
      dockerfile: services/notify/Notify.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JwtSettings__Secret=CF6F07A3B43D4A6B5F9F5DE7687A392C6E71E2AABD7D2D83CFB0F58B6CE6C369
      - Postgres__ConnectionString=Host=pg_db;Username=postgres;Password=postgres;Database=catalog; PORT=5432
      - AwsNotify__accessKey=
      - AwsNotify__secretKey=
      - AwsNotify__region=sa-east-1
      - AwsNotify__urlQueue=https://sqs.sa-east-1.amazonaws.com/653328364873
    ports:
      - "8083:80" 
    networks:
      - dev
    depends_on:
      - pg_db


volumes:
  pg-data: 
  redis-data:
  rabbitmq-data:   

networks:
  dev:
    driver: bridge
